### ISSUE TITLE
npm intall is showing errors

### ISSUE THREAD

**Issue by devarashetty** [jerairrest/react-chartjs-2#344]
`./util/has_lib.sh: line 31: pkg-config: command not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/Cellar/node/10.6.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sairam/react-chartjs-2/node_modules/canvas
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok 
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.12 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sairam/.npm/_logs/2018-10-04T04_30_26_771Z-debug.log`

**Comment by jerairrest** [comment]
You'll need canvas installed on your computer to be able to `npm install` this project.

on mac I believe it's just `brew install canvas`

**Comment by scottalan** [comment]
@jerairrest 

Wanted to contribute, but also having issues installing packages.

Same error:
```
Failed at the canvas@1.6.12 install script.
```
Do you happen to know if `goocanvas` will work?

![image](https://user-images.githubusercontent.com/247016/68403300-55f7e480-0142-11ea-8201-38858989cccf.png)

Thanks

**Comment by davnicwil** [comment]
Just in case anyone else runs into this, the relevant error was literally on line 1 in OPs error message `pkg-config: command not found` 

On macOS, for whatever reason, though I had `pkg-config` installed (`brew install pkg-config` did nothing as it was already installed) the `pkg-config` still wasn't available - even running `pkg-config --version` in the terminal returned this command not found error.

What fixed it for me was upgrading to the latest `pkg-config` (0.29.2) via `brew upgrade pkg-config` -- after that `pkg-config --version` worked in the terminal and `npm i` of this project worked just fine.

Strange one. I think it could have been an issue with the Homebrew formula for the previous version of `pkg-config` I was on (0.29.0 I think) that just didn't install it properly.
