### ISSUE TITLE
Failing to run tests

### ISSUE THREAD

**Issue by armenzg** [jerairrest/react-chartjs-2#349]
I have issues running `npm install` and `npm test`, however, I can run `npm start` without issues.

Failing to install:
```
armenzg@armenzg-mbp react-chartjs-2$ npm install

> canvas@1.6.13 install /Users/armenzg/repos/react-chartjs-2/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/armenzg/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/armenzg/.nvm/versions/node/v10.10.0/bin/node" "/Users/armenzg/.nvm/versions/node/v10.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/armenzg/repos/react-chartjs-2/node_modules/canvas
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/armenzg/.npm/_logs/2018-10-18T20_28_36_405Z-debug.log
```

Failing to run tests:
```
armenzg@armenzg-mbp react-chartjs-2$ npm test

> react-chartjs-2@2.7.4 test /Users/armenzg/repos/react-chartjs-2
> mocha test/config/setup.js test/__tests__/**/*

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../build/Release/canvas.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/armenzg/repos/react-chartjs-2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/node_modules/canvas-prebuilt/canvas/lib/canvas.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/armenzg/repos/react-chartjs-2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/test/config/setup.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/armenzg/repos/react-chartjs-2/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/armenzg/repos/react-chartjs-2/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/armenzg/repos/react-chartjs-2/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by armenzg** [comment]
I'm running this on my Mac.

**Comment by armenzg** [comment]
Installing cairo improve the situation when installing packages: `brew install cairo` [1].
I also switched my node version to 8 since there were a *lot* of deprecation warnings with node 10.

The test issues persist.

[1]
```
armenzg@armenzg-mbp react-chartjs-2$ npm install
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

audited 20143 packages in 12.723s
found 12 vulnerabilities (5 low, 1 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by jerairrest** [comment]
Hey @armenzg 

I'm glad you were able to figure out you needed canvas.

Can you please provide in detail some of the errors you are getting?

**Comment by armenzg** [comment]
You can see my original issue on the openning comment under "Failing to run tests:"

It seems that if I install packages with a specific version of node and then try to run with a different version of nodes the tests will not run.

I probably was switching between Node versions while I had not yet figured out that I needed cairo.

To fix this issue I was thinking of updating the README.md to say that cairo is a requirement to run tests and switching between Node versions can prevent you from running tests.

Does this work for you?

[1]
```
armenzg@armenzg-mbp react-chartjs-2$ npm test

> react-chartjs-2@2.7.4 test /Users/armenzg/repos/react-chartjs-2
> mocha test/config/setup.js test/__tests__/**/*

Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.


  <Chart />
    ✓ renders (134ms)
    ✓ renders chart on props.redraw(true) (118ms)
    ✓ renders on props.height change (49ms)
    ✓ renders on props.width change (60ms)
    ✓ renders on props.type change (51ms)
    ✓ renders on props.legend change (48ms)
    ✓ renders on props.options change (54ms)
    ✓ renders on props.data change (56ms)
    ✓ doesn't render when props didn't change (57ms)
    ✓ doesn't render when function references are changed (40ms)
    ✓ calls getDatasetAtEvent (71ms)
    ✓ calls getElementAtEvent (66ms)
    ✓ calls getElementsAtEvent (79ms)
    ✓ calls onElementsClick (98ms)
    props.data function
      ✓ calls data func with canvas node (47ms)
    checkDatasets
      ✓ should log error to console if datasets don't have a label (48ms)
      ✓ should not log error to console if all datasets have a label (43ms)
      ✓ should not log error to console if a custom datasetKeyProvider is provided (68ms)


  18 passing (2s)
```

[2] Installation output with Node 8
```
armenzg@armenzg-mbp react-chartjs-2$ rm -rf node_modules/
armenzg@armenzg-mbp react-chartjs-2$ npm install

> fsevents@1.2.4 install /Users/armenzg/repos/react-chartjs-2/node_modules/fsevents
> node install

[fsevents] Success: "/Users/armenzg/repos/react-chartjs-2/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> canvas@1.6.13 install /Users/armenzg/repos/react-chartjs-2/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
../src/Canvas.cc:221:19: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    closure->pfn->Call(1, argv);
                  ^
../../nan/nan.h:1654:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
...
Clipped out a lot of deprecation warnings
...
node-pre-gyp WARN Using request for node-pre-gyp https download
[canvas-prebuilt] Success: "/Users/armenzg/repos/react-chartjs-2/node_modules/canvas-prebuilt/canvas/build/Release/canvas-prebuilt.node" is installed via remote

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/armenzg/repos/react-chartjs-2/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

added 1646 packages from 1269 contributors and audited 20143 packages in 55.453s
found 12 vulnerabilities (5 low, 1 moderate, 5 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
armenzg@armenzg-mbp react-chartjs-2$ node --version
v8.12.0
armenzg@armenzg-mbp react-chartjs-2$ npm test

> react-chartjs-2@2.7.4 test /Users/armenzg/repos/react-chartjs-2
> mocha test/config/setup.js test/__tests__/**/*

Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.


  <Chart />
    ✓ renders (167ms)
    ✓ renders chart on props.redraw(true) (132ms)
    ✓ renders on props.height change (89ms)
    ✓ renders on props.width change (46ms)
    ✓ renders on props.type change (55ms)
    ✓ renders on props.legend change (50ms)
    ✓ renders on props.options change (47ms)
    ✓ renders on props.data change (57ms)
    ✓ doesn't render when props didn't change (45ms)
    ✓ doesn't render when function references are changed (44ms)
    ✓ calls getDatasetAtEvent (98ms)
    ✓ calls getElementAtEvent (89ms)
    ✓ calls getElementsAtEvent (89ms)
    ✓ calls onElementsClick (75ms)
    props.data function
      ✓ calls data func with canvas node (58ms)
    checkDatasets
      ✓ should log error to console if datasets don't have a label (83ms)
      ✓ should not log error to console if all datasets have a label (54ms)
      ✓ should not log error to console if a custom datasetKeyProvider is provided (43ms)


  18 passing (2s)
armenzg@armenzg-mbp react-chartjs-2$ nvm use 10
Now using node v10.10.0 (npm v6.4.1)
armenzg@armenzg-mbp react-chartjs-2$ npm test

> react-chartjs-2@2.7.4 test /Users/armenzg/repos/react-chartjs-2
> mocha test/config/setup.js test/__tests__/**/*

internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/armenzg/repos/react-chartjs-2/node_modules/canvas-prebuilt/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/armenzg/repos/react-chartjs-2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/node_modules/canvas-prebuilt/canvas/lib/canvas.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/armenzg/repos/react-chartjs-2/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/test/config/setup.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/armenzg/repos/react-chartjs-2/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/armenzg/repos/react-chartjs-2/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/armenzg/repos/react-chartjs-2/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/armenzg/repos/react-chartjs-2/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
npm ERR! Test failed.  See above for more details.
```

**Comment by Pringels** [comment]
Closing for now. The test setup will be overhauled soon.
