### ISSUE TITLE
npm run build appears to be broken after fresh npm install on master

### ISSUE THREAD

**Issue by davnicwil** [jerairrest/react-chartjs-2#509]
Fresh clone, on master.

Run `npm i`

Run `npm run build`

Get the following error for `uglify` - `warnings not a supported option`

```
src/index.js → dist/react-chartjs-2.min.js...
[!] (uglify plugin) Error: Error transforming bundle with 'uglify' plugin: `warnings` is not a supported option
Error: Error transforming bundle with 'uglify' plugin: `warnings` is not a supported option
    at error (/my--path/react-chartjs-2/node_modules/rollup/dist/rollup.js:181:12)
    at /my--path/react-chartjs-2/node_modules/rollup/dist/rollup.js:9494:5
```

**Comment by davnicwil** [comment]
[Opened a PR](https://github.com/jerairrest/react-chartjs-2/pull/510) that fixes this.

The `warnings` option moved in uglify from `options.compress` to the top level `options` object.
